version: '2'
services:
    # APIServer_nginx
    nginx_forunit:
        build: "nginx_custom"
        image: "nginx_forunit"
        # restart: "no"
        # expose:
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "unitpy_api"

    # APIServer_unitpy_api
    unitpy_api:
        build: "unitpy_custom"
        image: "unitpy_api"
        restart: "no"
        expose:
            - "8300"
