---
swagger: "2.0"
info:
  version: "2018-11-23T03:08:58Z"
  title: "EeveeAPI"
host: "liuncvp3x8.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/EeveeStageProd"
schemes:
- "https"
paths:
  /eeveeget:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
