---
swagger: "2.0"
info:
  version: "1.0"
  title: "yadongetall"
host: "ww24h3me17.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/Stage"
schemes:
- "https"
paths:
  /yadonget:
    post:
      responses:
        200:
          description: "200 response"
